### ISSUE TITLE
Changed token format (laravel_sanctum_*) appears not to be accepted by the plugin

### ISSUE THREAD

**Issue by oldchaprk** [anonaddy/browser-extension#42]

**Comment by willbrowningme** [comment]
Thanks a lot for bringing this to my attention. It seems it was introduced in [v3.2.6](https://github.com/laravel/sanctum/releases/tag/v3.2.6) of Laravel Sanctum released yesterday. I think that the change should have been released in a major version of Sanctum as it may have broken a number of API clients out there.

I've actually set the token prefix to be `addy_io_` instead of the default `laravel_sanctum_` and pushed the fix to this repo. The Firefox and Chrome extensions should be updated soon too.
